# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  - 7.4

install:
  - composer install

script:
  - composer phpcs-dry
  - vendor/bin/phpunit --no-coverage
