<?php
/**
 * OrderShippingPositionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Client\Channel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SCX Channel API
 *
 * SCX Channel API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Client\Channel\Model;

use PHPUnit\Framework\TestCase;

/**
 * OrderShippingPositionTest Class Doc Comment
 *
 * @category    Class
 * @description OrderShippingPosition
 * @package     JTL\SCX\Client\Channel
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Client\Channel\Model\OrderShippingPosition
 */
class OrderShippingPositionTest extends TestCase
{



    /**
     * Test attribute "carrier"
     * @test
     */
    public function it_has_a_Carrier(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new OrderShippingPosition(['carrier' => $sample]);

        $this->assertMethodExists($sut, 'getCarrier');
        $this->assertSame($sample, $sut->getCarrier());

        $this->assertArrayHasKey('carrier', $sut);
        $this->assertSame($sample, $sut['carrier']);

    }

    /**
     * Test attribute "carrier"
     * @test
     */
    public function it_has_a_setter_for_Carrier(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new OrderShippingPosition();

        $this->assertMethodExists($sut, 'setCarrier');
        $sut->setCarrier($sample);
        $this->assertSame($sample, $sut['carrier']);
    }


    /**
     * Test attribute "trackingNumber"
     * @test
     */
    public function it_has_a_TrackingNumber(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new OrderShippingPosition(['trackingNumber' => $sample]);

        $this->assertMethodExists($sut, 'getTrackingNumber');
        $this->assertSame($sample, $sut->getTrackingNumber());

        $this->assertArrayHasKey('trackingNumber', $sut);
        $this->assertSame($sample, $sut['trackingNumber']);

    }

    /**
     * Test attribute "trackingNumber"
     * @test
     */
    public function it_has_a_setter_for_TrackingNumber(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new OrderShippingPosition();

        $this->assertMethodExists($sut, 'setTrackingNumber');
        $sut->setTrackingNumber($sample);
        $this->assertSame($sample, $sut['trackingNumber']);
    }


    /**
     * Test attribute "returnTracking"
     * @test
     */
    public function it_has_a_ReturnTracking(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\OrderShippingReturnTracking');
        $sut = new OrderShippingPosition(['returnTracking' => $sample]);

        $this->assertMethodExists($sut, 'getReturnTracking');
        $this->assertSame($sample, $sut->getReturnTracking());

        $this->assertArrayHasKey('returnTracking', $sut);
        $this->assertSame($sample, $sut['returnTracking']);

    }

    /**
     * Test attribute "returnTracking"
     * @test
     */
    public function it_has_a_setter_for_ReturnTracking(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\OrderShippingReturnTracking');
        $sut = new OrderShippingPosition();

        $this->assertMethodExists($sut, 'setReturnTracking');
        $sut->setReturnTracking($sample);
        $this->assertSame($sample, $sut['returnTracking']);
    }


    /**
     * Test attribute "shippedAt"
     * @test
     */
    public function it_has_a_ShippedAt(): void
    {
        $sample = $this->buildSampleForDataType('\DateTime');
        $sut = new OrderShippingPosition(['shippedAt' => $sample]);

        $this->assertMethodExists($sut, 'getShippedAt');
        $this->assertSame($sample, $sut->getShippedAt());

        $this->assertArrayHasKey('shippedAt', $sut);
        $this->assertSame($sample, $sut['shippedAt']);

    }

    /**
     * Test attribute "shippedAt"
     * @test
     */
    public function it_has_a_setter_for_ShippedAt(): void
    {
        $sample = $this->buildSampleForDataType('\DateTime');
        $sut = new OrderShippingPosition();

        $this->assertMethodExists($sut, 'setShippedAt');
        $sut->setShippedAt($sample);
        $this->assertSame($sample, $sut['shippedAt']);
    }


    /**
     * Test attribute "orderItemIdList"
     * @test
     */
    public function it_has_a_OrderItemIdList(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\OrderShippingPositionItem[]');
        $sut = new OrderShippingPosition(['orderItemIdList' => $sample]);

        $this->assertMethodExists($sut, 'getOrderItemIdList');
        $this->assertSame($sample, $sut->getOrderItemIdList());

        $this->assertArrayHasKey('orderItemIdList', $sut);
        $this->assertSame($sample, $sut['orderItemIdList']);

    }

    /**
     * Test attribute "orderItemIdList"
     * @test
     */
    public function it_has_a_setter_for_OrderItemIdList(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\OrderShippingPositionItem[]');
        $sut = new OrderShippingPosition();

        $this->assertMethodExists($sut, 'setOrderItemIdList');
        $sut->setOrderItemIdList($sample);
        $this->assertSame($sample, $sut['orderItemIdList']);
    }


    /**
     * Test attribute "shippedFrom"
     * @test
     */
    public function it_has_a_ShippedFrom(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\OrderShippingShippedFrom');
        $sut = new OrderShippingPosition(['shippedFrom' => $sample]);

        $this->assertMethodExists($sut, 'getShippedFrom');
        $this->assertSame($sample, $sut->getShippedFrom());

        $this->assertArrayHasKey('shippedFrom', $sut);
        $this->assertSame($sample, $sut['shippedFrom']);

    }

    /**
     * Test attribute "shippedFrom"
     * @test
     */
    public function it_has_a_setter_for_ShippedFrom(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\OrderShippingShippedFrom');
        $sut = new OrderShippingPosition();

        $this->assertMethodExists($sut, 'setShippedFrom');
        $sut->setShippedFrom($sample);
        $this->assertSame($sample, $sut['shippedFrom']);
    }

    private function assertMethodExists(OrderShippingPosition $sut, string $methodName): void
    {
        try {
            $_ = (new \ReflectionClass($sut))->getMethod($methodName);
        } catch (\ReflectionException $e) {
            self::fail("No public method {$methodName} found in " . get_class($sut));
        }
        $this->assertTrue(true);
    }

    private function buildSampleForDataType(string $dataType)
    {
        $isArray = substr($dataType, -2) === '[]';

        if ($isArray) {
            $dataType = substr($dataType, 0, strlen($dataType)-2);
        }

        $isMap = substr($dataType, 0, 3) === 'map';
        if ($isMap) {
            $isArray = true;
            $dataType = 'string';
        }

        switch ($dataType) {
            case '\SplFileObject':
                $sampleData = new \SplFileObject('php://memory');
                break;
            case 'object':
                $sampleData = $this->createStub('\stdClass');
                break;
            case 'integer':
            case 'int':
                $sampleData = random_int(100, 10000);
                break;
            case 'double':
            case 'float':
                $sampleData = random_int(100, 10000)/pi();
                break;
            case 'bool':
            case 'boolean':
                $sampleData = (bool)random_int(0, 1);
                break;
            case 'string':
            case 'text':
                $sampleData = uniqid('a_string');
                break;
            default:
                $sampleData = $this->createStub($dataType);
        }

        if ($isArray) {
            $sampleData = [$sampleData];
        }
        return $sampleData;
    }
}
