<?php
/**
 * OrderShippingShippedFromTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Client\Channel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SCX Channel API
 *
 * SCX Channel API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Client\Channel\Model;

use PHPUnit\Framework\TestCase;

/**
 * OrderShippingShippedFromTest Class Doc Comment
 *
 * @category    Class
 * @description The adress from where the shipment is sent.
 * @package     JTL\SCX\Client\Channel
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Client\Channel\Model\OrderShippingShippedFrom
 */
class OrderShippingShippedFromTest extends TestCase
{



    /**
     * Test attribute "city"
     * @test
     */
    public function it_has_a_City(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new OrderShippingShippedFrom(['city' => $sample]);

        $this->assertMethodExists($sut, 'getCity');
        $this->assertSame($sample, $sut->getCity());

        $this->assertArrayHasKey('city', $sut);
        $this->assertSame($sample, $sut['city']);

    }

    /**
     * Test attribute "city"
     * @test
     */
    public function it_has_a_setter_for_City(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new OrderShippingShippedFrom();

        $this->assertMethodExists($sut, 'setCity');
        $sut->setCity($sample);
        $this->assertSame($sample, $sut['city']);
    }


    /**
     * Test attribute "country"
     * @test
     */
    public function it_has_a_Country(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new OrderShippingShippedFrom(['country' => $sample]);

        $this->assertMethodExists($sut, 'getCountry');
        $this->assertSame($sample, $sut->getCountry());

        $this->assertArrayHasKey('country', $sut);
        $this->assertSame($sample, $sut['country']);

    }

    /**
     * Test attribute "country"
     * @test
     */
    public function it_has_a_setter_for_Country(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new OrderShippingShippedFrom();

        $this->assertMethodExists($sut, 'setCountry');
        $sut->setCountry($sample);
        $this->assertSame($sample, $sut['country']);
    }


    /**
     * Test attribute "postcode"
     * @test
     */
    public function it_has_a_Postcode(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new OrderShippingShippedFrom(['postcode' => $sample]);

        $this->assertMethodExists($sut, 'getPostcode');
        $this->assertSame($sample, $sut->getPostcode());

        $this->assertArrayHasKey('postcode', $sut);
        $this->assertSame($sample, $sut['postcode']);

    }

    /**
     * Test attribute "postcode"
     * @test
     */
    public function it_has_a_setter_for_Postcode(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new OrderShippingShippedFrom();

        $this->assertMethodExists($sut, 'setPostcode');
        $sut->setPostcode($sample);
        $this->assertSame($sample, $sut['postcode']);
    }

    private function assertMethodExists(OrderShippingShippedFrom $sut, string $methodName): void
    {
        try {
            $_ = (new \ReflectionClass($sut))->getMethod($methodName);
        } catch (\ReflectionException $e) {
            self::fail("No public method {$methodName} found in " . get_class($sut));
        }
        $this->assertTrue(true);
    }

    private function buildSampleForDataType(string $dataType)
    {
        $isArray = substr($dataType, -2) === '[]';

        if ($isArray) {
            $dataType = substr($dataType, 0, strlen($dataType)-2);
        }

        $isMap = substr($dataType, 0, 3) === 'map';
        if ($isMap) {
            $isArray = true;
            $dataType = 'string';
        }

        switch ($dataType) {
            case '\SplFileObject':
                $sampleData = new \SplFileObject('php://memory');
                break;
            case 'object':
                $sampleData = $this->createStub('\stdClass');
                break;
            case 'integer':
            case 'int':
                $sampleData = random_int(100, 10000);
                break;
            case 'double':
            case 'float':
                $sampleData = random_int(100, 10000)/pi();
                break;
            case 'bool':
            case 'boolean':
                $sampleData = (bool)random_int(0, 1);
                break;
            case 'string':
            case 'text':
                $sampleData = uniqid('a_string');
                break;
            default:
                $sampleData = $this->createStub($dataType);
        }

        if ($isArray) {
            $sampleData = [$sampleData];
        }
        return $sampleData;
    }
}
