<?php
/**
 * PriceContainerTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Client\Channel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SCX Channel API
 *
 * SCX Channel API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Client\Channel\Model;

use PHPUnit\Framework\TestCase;

/**
 * PriceContainerTest Class Doc Comment
 *
 * @category    Class
 * @description PriceContainer
 * @package     JTL\SCX\Client\Channel
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Client\Channel\Model\PriceContainer
 */
class PriceContainerTest extends TestCase
{



    /**
     * Test attribute "id"
     * @test
     */
    public function it_has_a_Id(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new PriceContainer(['id' => $sample]);

        $this->assertMethodExists($sut, 'getId');
        $this->assertSame($sample, $sut->getId());

        $this->assertArrayHasKey('id', $sut);
        $this->assertSame($sample, $sut['id']);

    }

    /**
     * Test attribute "id"
     * @test
     */
    public function it_has_a_setter_for_Id(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new PriceContainer();

        $this->assertMethodExists($sut, 'setId');
        $sut->setId($sample);
        $this->assertSame($sample, $sut['id']);
    }


    /**
     * Test attribute "quantityPriceList"
     * @test
     */
    public function it_has_a_QuantityPriceList(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\QuantityPrice[]');
        $sut = new PriceContainer(['quantityPriceList' => $sample]);

        $this->assertMethodExists($sut, 'getQuantityPriceList');
        $this->assertSame($sample, $sut->getQuantityPriceList());

        $this->assertArrayHasKey('quantityPriceList', $sut);
        $this->assertSame($sample, $sut['quantityPriceList']);

    }

    /**
     * Test attribute "quantityPriceList"
     * @test
     */
    public function it_has_a_setter_for_QuantityPriceList(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\QuantityPrice[]');
        $sut = new PriceContainer();

        $this->assertMethodExists($sut, 'setQuantityPriceList');
        $sut->setQuantityPriceList($sample);
        $this->assertSame($sample, $sut['quantityPriceList']);
    }

    private function assertMethodExists(PriceContainer $sut, string $methodName): void
    {
        try {
            $_ = (new \ReflectionClass($sut))->getMethod($methodName);
        } catch (\ReflectionException $e) {
            self::fail("No public method {$methodName} found in " . get_class($sut));
        }
        $this->assertTrue(true);
    }

    private function buildSampleForDataType(string $dataType)
    {
        $isArray = substr($dataType, -2) === '[]';

        if ($isArray) {
            $dataType = substr($dataType, 0, strlen($dataType)-2);
        }

        $isMap = substr($dataType, 0, 3) === 'map';
        if ($isMap) {
            $isArray = true;
            $dataType = 'string';
        }

        switch ($dataType) {
            case '\SplFileObject':
                $sampleData = new \SplFileObject('php://memory');
                break;
            case 'object':
                $sampleData = $this->createStub('\stdClass');
                break;
            case 'integer':
            case 'int':
                $sampleData = random_int(100, 10000);
                break;
            case 'double':
            case 'float':
                $sampleData = random_int(100, 10000)/pi();
                break;
            case 'bool':
            case 'boolean':
                $sampleData = (bool)random_int(0, 1);
                break;
            case 'string':
            case 'text':
                $sampleData = uniqid('a_string');
                break;
            default:
                $sampleData = $this->createStub($dataType);
        }

        if ($isArray) {
            $sampleData = [$sampleData];
        }
        return $sampleData;
    }
}
