<?php
/**
 * VariationTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  JTL\SCX\Client\Channel
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SCX Channel API
 *
 * SCX Channel API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace JTL\SCX\Client\Channel\Model;

use PHPUnit\Framework\TestCase;

/**
 * VariationTest Class Doc Comment
 *
 * @category    Class
 * @description Variation
 * @package     JTL\SCX\Client\Channel
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 * @covers      \JTL\SCX\Client\Channel\Model\Variation
 */
class VariationTest extends TestCase
{



    /**
     * Test attribute "offerId"
     * @test
     */
    public function it_has_a_OfferId(): void
    {
        $sample = $this->buildSampleForDataType('int');
        $sut = new Variation(['offerId' => $sample]);

        $this->assertMethodExists($sut, 'getOfferId');
        $this->assertSame($sample, $sut->getOfferId());

        $this->assertArrayHasKey('offerId', $sut);
        $this->assertSame($sample, $sut['offerId']);

    }

    /**
     * Test attribute "offerId"
     * @test
     */
    public function it_has_a_setter_for_OfferId(): void
    {
        $sample = $this->buildSampleForDataType('int');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setOfferId');
        $sut->setOfferId($sample);
        $this->assertSame($sample, $sut['offerId']);
    }


    /**
     * Test attribute "sku"
     * @test
     */
    public function it_has_a_Sku(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation(['sku' => $sample]);

        $this->assertMethodExists($sut, 'getSku');
        $this->assertSame($sample, $sut->getSku());

        $this->assertArrayHasKey('sku', $sut);
        $this->assertSame($sample, $sut['sku']);

    }

    /**
     * Test attribute "sku"
     * @test
     */
    public function it_has_a_setter_for_Sku(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setSku');
        $sut->setSku($sample);
        $this->assertSame($sample, $sut['sku']);
    }


    /**
     * Test attribute "gtin"
     * @test
     */
    public function it_has_a_Gtin(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation(['gtin' => $sample]);

        $this->assertMethodExists($sut, 'getGtin');
        $this->assertSame($sample, $sut->getGtin());

        $this->assertArrayHasKey('gtin', $sut);
        $this->assertSame($sample, $sut['gtin']);

    }

    /**
     * Test attribute "gtin"
     * @test
     */
    public function it_has_a_setter_for_Gtin(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setGtin');
        $sut->setGtin($sample);
        $this->assertSame($sample, $sut['gtin']);
    }


    /**
     * Test attribute "variationDimensionList"
     * @test
     */
    public function it_has_a_VariationDimensionList(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\ChannelAttribute[]');
        $sut = new Variation(['variationDimensionList' => $sample]);

        $this->assertMethodExists($sut, 'getVariationDimensionList');
        $this->assertSame($sample, $sut->getVariationDimensionList());

        $this->assertArrayHasKey('variationDimensionList', $sut);
        $this->assertSame($sample, $sut['variationDimensionList']);

    }

    /**
     * Test attribute "variationDimensionList"
     * @test
     */
    public function it_has_a_setter_for_VariationDimensionList(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\ChannelAttribute[]');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setVariationDimensionList');
        $sut->setVariationDimensionList($sample);
        $this->assertSame($sample, $sut['variationDimensionList']);
    }


    /**
     * Test attribute "quantity"
     * @test
     */
    public function it_has_a_Quantity(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation(['quantity' => $sample]);

        $this->assertMethodExists($sut, 'getQuantity');
        $this->assertSame($sample, $sut->getQuantity());

        $this->assertArrayHasKey('quantity', $sut);
        $this->assertSame($sample, $sut['quantity']);

    }

    /**
     * Test attribute "quantity"
     * @test
     */
    public function it_has_a_setter_for_Quantity(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setQuantity');
        $sut->setQuantity($sample);
        $this->assertSame($sample, $sut['quantity']);
    }


    /**
     * Test attribute "priceList"
     * @test
     */
    public function it_has_a_PriceList(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\PriceContainer[]');
        $sut = new Variation(['priceList' => $sample]);

        $this->assertMethodExists($sut, 'getPriceList');
        $this->assertSame($sample, $sut->getPriceList());

        $this->assertArrayHasKey('priceList', $sut);
        $this->assertSame($sample, $sut['priceList']);

    }

    /**
     * Test attribute "priceList"
     * @test
     */
    public function it_has_a_setter_for_PriceList(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\PriceContainer[]');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setPriceList');
        $sut->setPriceList($sample);
        $this->assertSame($sample, $sut['priceList']);
    }


    /**
     * Test attribute "taxPercent"
     * @test
     */
    public function it_has_a_TaxPercent(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation(['taxPercent' => $sample]);

        $this->assertMethodExists($sut, 'getTaxPercent');
        $this->assertSame($sample, $sut->getTaxPercent());

        $this->assertArrayHasKey('taxPercent', $sut);
        $this->assertSame($sample, $sut['taxPercent']);

    }

    /**
     * Test attribute "taxPercent"
     * @test
     */
    public function it_has_a_setter_for_TaxPercent(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setTaxPercent');
        $sut->setTaxPercent($sample);
        $this->assertSame($sample, $sut['taxPercent']);
    }


    /**
     * Test attribute "pictureList"
     * @test
     */
    public function it_has_a_PictureList(): void
    {
        $sample = $this->buildSampleForDataType('string[]');
        $sut = new Variation(['pictureList' => $sample]);

        $this->assertMethodExists($sut, 'getPictureList');
        $this->assertSame($sample, $sut->getPictureList());

        $this->assertArrayHasKey('pictureList', $sut);
        $this->assertSame($sample, $sut['pictureList']);

    }

    /**
     * Test attribute "pictureList"
     * @test
     */
    public function it_has_a_setter_for_PictureList(): void
    {
        $sample = $this->buildSampleForDataType('string[]');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setPictureList');
        $sut->setPictureList($sample);
        $this->assertSame($sample, $sut['pictureList']);
    }


    /**
     * Test attribute "title"
     * @test
     */
    public function it_has_a_Title(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation(['title' => $sample]);

        $this->assertMethodExists($sut, 'getTitle');
        $this->assertSame($sample, $sut->getTitle());

        $this->assertArrayHasKey('title', $sut);
        $this->assertSame($sample, $sut['title']);

    }

    /**
     * Test attribute "title"
     * @test
     */
    public function it_has_a_setter_for_Title(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setTitle');
        $sut->setTitle($sample);
        $this->assertSame($sample, $sut['title']);
    }


    /**
     * Test attribute "subTitle"
     * @test
     */
    public function it_has_a_SubTitle(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation(['subTitle' => $sample]);

        $this->assertMethodExists($sut, 'getSubTitle');
        $this->assertSame($sample, $sut->getSubTitle());

        $this->assertArrayHasKey('subTitle', $sut);
        $this->assertSame($sample, $sut['subTitle']);

    }

    /**
     * Test attribute "subTitle"
     * @test
     */
    public function it_has_a_setter_for_SubTitle(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setSubTitle');
        $sut->setSubTitle($sample);
        $this->assertSame($sample, $sut['subTitle']);
    }


    /**
     * Test attribute "description"
     * @test
     */
    public function it_has_a_Description(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation(['description' => $sample]);

        $this->assertMethodExists($sut, 'getDescription');
        $this->assertSame($sample, $sut->getDescription());

        $this->assertArrayHasKey('description', $sut);
        $this->assertSame($sample, $sut['description']);

    }

    /**
     * Test attribute "description"
     * @test
     */
    public function it_has_a_setter_for_Description(): void
    {
        $sample = $this->buildSampleForDataType('string');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setDescription');
        $sut->setDescription($sample);
        $this->assertSame($sample, $sut['description']);
    }


    /**
     * Test attribute "channelAttributeList"
     * @test
     */
    public function it_has_a_ChannelAttributeList(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\ChannelAttribute[]');
        $sut = new Variation(['channelAttributeList' => $sample]);

        $this->assertMethodExists($sut, 'getChannelAttributeList');
        $this->assertSame($sample, $sut->getChannelAttributeList());

        $this->assertArrayHasKey('channelAttributeList', $sut);
        $this->assertSame($sample, $sut['channelAttributeList']);

    }

    /**
     * Test attribute "channelAttributeList"
     * @test
     */
    public function it_has_a_setter_for_ChannelAttributeList(): void
    {
        $sample = $this->buildSampleForDataType('\JTL\SCX\Client\Channel\Model\ChannelAttribute[]');
        $sut = new Variation();

        $this->assertMethodExists($sut, 'setChannelAttributeList');
        $sut->setChannelAttributeList($sample);
        $this->assertSame($sample, $sut['channelAttributeList']);
    }

    private function assertMethodExists(Variation $sut, string $methodName): void
    {
        try {
            $_ = (new \ReflectionClass($sut))->getMethod($methodName);
        } catch (\ReflectionException $e) {
            self::fail("No public method {$methodName} found in " . get_class($sut));
        }
        $this->assertTrue(true);
    }

    private function buildSampleForDataType(string $dataType)
    {
        $isArray = substr($dataType, -2) === '[]';

        if ($isArray) {
            $dataType = substr($dataType, 0, strlen($dataType)-2);
        }

        $isMap = substr($dataType, 0, 3) === 'map';
        if ($isMap) {
            $isArray = true;
            $dataType = 'string';
        }

        switch ($dataType) {
            case '\SplFileObject':
                $sampleData = new \SplFileObject('php://memory');
                break;
            case 'object':
                $sampleData = $this->createStub('\stdClass');
                break;
            case 'integer':
            case 'int':
                $sampleData = random_int(100, 10000);
                break;
            case 'double':
            case 'float':
                $sampleData = random_int(100, 10000)/pi();
                break;
            case 'bool':
            case 'boolean':
                $sampleData = (bool)random_int(0, 1);
                break;
            case 'string':
            case 'text':
                $sampleData = uniqid('a_string');
                break;
            default:
                $sampleData = $this->createStub($dataType);
        }

        if ($isArray) {
            $sampleData = [$sampleData];
        }
        return $sampleData;
    }
}
