name: PHPUnit
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v1
            - name: PHPUnit
              run: ./vendor/bin/phpunit
              shell: bash
