name: PHPUnit
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v1
            - name: ls
              run: pwd; ls -la
              shell: bash
            - uses: php-actions/phpunit@v8
              with:
                configuration: phpunit.xml
